{+CR} More implementations and optimizations
What in the world is this:

java.lang.NullPointerException: Cannot invoke "tripleo.elijah.stages.gen_fn.DeferredObject2.then(org.jdeferred2.DoneCallback)" because "this.onFunctionInvocations" is null
	at tripleo.elijah.stages.gen_fn.ProcTableEntry.onFunctionInvocation(ProcTableEntry.java:181)
	at tripleo.elijah.stages.deduce.DeduceProcCall.<init>(DeduceProcCall.java:56)
	at tripleo.elijah.stages.gen_fn.ProcTableEntry.<init>(ProcTableEntry.java:68)
	at tripleo.elijah.stages.gen_fn.GenerateFunctions.addProcTableEntry(GenerateFunctions.java:2696)
	at tripleo.elijah.stages.gen_fn.GenerateFunctions.expression_to_call_add_entry(GenerateFunctions.java:2715)
	at tripleo.elijah.stages.gen_fn.GenerateFunctions.expression_to_call(GenerateFunctions.java:2800)
	at tripleo.elijah.stages.gen_fn.GenerateFunctions.assign_variable(GenerateFunctions.java:2568)
	at tripleo.elijah.stages.gen_fn.GenerateFunctions$Generate_Item.generate_variable_sequence(GenerateFunctions.java:3168)
	at tripleo.elijah.stages.gen_fn.GenerateFunctions.generate_item(GenerateFunctions.java:1966)
	at tripleo.elijah.stages.gen_fn.GenerateFunctions.generateFunction(GenerateFunctions.java:2121)
	at tripleo.elijah.stages.gen_fn.WlGenerateFunction.run(WlGenerateFunction.java:56)
	at tripleo.elijah.work.WorkManager.drain(WorkManager.java:56)
	at tripleo.elijah.entrypoints.EntryPointList.generateFromEntryPoints(EntryPointList.java:63)
	at tripleo.elijah.entrypoints.EntryPointList.generate(EntryPointList.java:29)
	at tripleo.elijah.stages.gen_fn.GenerateFunctions.generateFromEntryPoints(GenerateFunctions.java:1861)
	at tripleo.elijah.comp.DeducePipeline$PL_Run2.run2(DeducePipeline.java:123)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at tripleo.elijah.comp.DeducePipeline.run(DeducePipeline.java:70)
	at tripleo.elijah.comp.Pipeline.run(Pipeline.java:32)
	at tripleo.elijah.comp.OStageProcess.lambda$run$0(CompilationHelp.java:157)
	at org.jdeferred2.impl.AbstractPromise.triggerDone(AbstractPromise.java:106)
	at org.jdeferred2.impl.AbstractPromise.done(AbstractPromise.java:65)
	at org.jdeferred2.impl.AbstractPromise.then(AbstractPromise.java:168)
	at tripleo.elijah.util.Eventual.then(Eventual.java:16)
	at tripleo.elijah.comp.i.CompilationEnclosure.waitPipelineLogic(CompilationEnclosure.java:518)
	at tripleo.elijah.comp.AccessBus.subscribePipelineLogic(AccessBus.java:32)
	at tripleo.elijah.comp.OStageProcess.run(CompilationHelp.java:152)
	at tripleo.elijah.comp.RuntimeProcesses.run_better(CompilationHelp.java:70)
	at tripleo.elijah.comp.CompilationRunner$CR_RunBetterAction.execute(CompilationRunner.java:363)
	at tripleo.elijah.comp.ActionWrapper2.execute(ActionWrapper2.java:21)
	at tripleo.elijah.comp.ICompilationBus$CB_Process.execute(ICompilationBus.java:38)
	at tripleo.elijah.comp.internal.CompilationBus.lambda$run_all$0(CompilationBus.java:65)
	at java.base/java.lang.Thread.run(Thread.java:833)